### ISSUE TITLE
Connections between SCT013 and ADS1015

### ISSUE THREAD

**Issue by kaminetzky** [pahowart/ampread#1]
Hello Paul!

First of all, thank you very much for this astounding repository! I'm developing a project that uses an SCT013 and an ADS1015 so it is helping me a lot.

Are you connecting the SCT013 directly to the ADS1015?

Cheers!

**Comment by francoromito** [comment]
Hi! I'm starting to connect SCT013 to ADS1015 (instead MCP3008...) with Raspberry Pi 3, any suggestion?? Thank you so much!

**Comment by pahowart** [comment]
The sensors are connected directly to raspberry pi using the headphone jack style connector. I have uploaded a couple of pictures of the finished build and the sensor that I used.

**Comment by Nakul93** [comment]
hello @pahowart 
I am using a SCT-013-000 so what changes should be made in code.
Please also tell me how to connect sct to ads1015 should we connect 1 wire to analog i/p of ads1015 and other to GND?
